### ISSUE TITLE
Twitch emotes being funky

### ISSUE THREAD

**Issue by Cloudhunter** [blay09/EiraMoticons#40]
Hi!

While trying out your mod for the first time as part of Project Ozone, I saw an issue where Twitch emotes weren't displaying.

After some debugging, I think I have identified the issue. It appears that Twitch Emotes now returns a full https url in their API, like so:

`https:\/\/static-cdn.jtvnw.net\/emoticons\/v1\/{image_id}\/1.0`

(Excuse the mangling, copied straight from a file).

https://github.com/blay09/EiraMoticons/blob/mc1710/src/main/java/net/blay09/mods/eiramoticons/addon/pack/TwitchGlobalPack.java#L52

On this line, "http:" is added before the returned URL in order to create a "template". This obviously results in an invalid URL.

Changing it not to add "http:" before should fix the issue. If you would like me to do a pull request using GitHub's editor, please let me know and I will happily do so.

Thanks!

**Comment by BlayTheNinth** [comment]
Thanks! New version is up on [Jenkins](http://jenkins.blay09.net/) and will be on CurseForge in a bit.

**Comment by Cloudhunter** [comment]
Thanks a bunch!
