### ISSUE TITLE
When Twitch is down loading a pack locks

### ISSUE THREAD

**Issue by cassgenerator** [blay09/EiraMoticons#48]
When the Twitch servers are unresponsive the mod locks up during the Post Initialization phase.
![capture](https://user-images.githubusercontent.com/1308624/29901782-44577062-8e3d-11e7-8932-b6b54d04a866.PNG)

**Comment by cassgenerator** [comment]
I should mention this was in Project Ozone 2 version 2.3.0 if that helps.

**Comment by BlayTheNinth** [comment]
What mod version is it though? Also this issue has been fixed in later Minecraft versions, and only happens very rarely. I don't think fixing it is worth it at this point.

**Comment by BlayTheNinth** [comment]
Actually, with the upcoming Twitch API deprecation, I'll fix it at least up until 1.7.10.

**Comment by BlayTheNinth** [comment]
Eh. They killed off the old API fully instead of providing a final state, so emotes aren't working now anyways. Just remove the mod from 1.7.10 unless someone wants to backport the API upgrade.
